SELECT * FROM Customer limit 20


--Q1. what is the total revenue generated by male vs. female customer?
SELECT gender, SUM("purchase_amount_(usd)") AS revenue
FROM customer
GROUP BY gender;


--Q2. Which customer used a discount but still spent more than the average purchases amount?
SELECT customer_id, "purchase_amount_(usd)"
FROM customer
WHERE discount_applied = 'Yes'
AND "purchase_amount_(usd)" >= (
    SELECT AVG("purchase_amount_(usd)")
    FROM customer
);

--Q3. which are the top 5 Products with the highest average review rating?
SELECT item_purchased,
ROUND(AVG(review_rating)::numeric, 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;



--Q4. Compare the average Purchaes Amounts between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


--Q5. Do subscribe customer spend more? Compare average spend and total revenue between subscribers and non-subscibers
--Q6. which 5 product have the highest